import { defineArrayMember, defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork",
  title: "作品管理",
  type: "document",
  fields: [
    defineField({
      name: "siteKey",
      title: "所属网站标识",
      type: "string",
      initialValue: "main",
      validation: (rule) => rule.required(),
      description: "当前网站填写 main；第二个网站填写对应的网站标识。",
    }),
    defineField({
      name: "featured",
      title: "设为精选作品",
      type: "boolean",
      initialValue: false,
      description: "开启后会优先显示在作品区顶部的大图位置。",
    }),
    defineField({
      name: "displayOrder",
      title: "排序数字",
      type: "number",
      initialValue: 100,
      description: "数字越小越靠前；不确定可保持默认。",
    }),
    defineField({
      name: "titleEn",
      title: "作品标题（英文）",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "titleZh", title: "作品标题（中文）", type: "string" }),
    defineField({
      name: "category",
      title: "作品分类",
      type: "string",
      options: {
        list: [
          { title: "主视觉", value: "Key Visual" },
          { title: "委托", value: "Commission" },
          { title: "界面细节", value: "UI Detail" },
          { title: "角色图", value: "Character Art" },
          { title: "设定参考", value: "Reference Sheet" },
          { title: "封面图", value: "Cover Art" },
          { title: "直播素材", value: "Stream Asset" },
          { title: "草稿", value: "Sketch" },
          { title: "个人作品", value: "Personal Work" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "thumbnail",
      title: "作品缩略图",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
      description: "用于作品列表展示。",
    }),
    defineField({
      name: "fullImage",
      title: "详情大图",
      type: "image",
      options: { hotspot: true },
      description: "用于点击作品后弹窗展示；不填时会使用缩略图。",
    }),
    defineField({
      name: "descriptionEn",
      title: "作品介绍（英文）",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "descriptionZh",
      title: "作品介绍（中文）",
      type: "text",
      rows: 3,
    }),
    defineField({ name: "roleEn", title: "制作内容 / 角色（英文）", type: "string" }),
    defineField({ name: "roleZh", title: "制作内容 / 角色（中文）", type: "string" }),
    defineField({ name: "clientEn", title: "客户 / 用途（英文）", type: "string" }),
    defineField({ name: "clientZh", title: "客户 / 用途（中文）", type: "string" }),
    defineField({ name: "creator", title: "作者 / 画师", type: "string" }),
    defineField({ name: "createdAt", title: "完成日期", type: "date" }),
    defineField({
      name: "tags",
      title: "标签",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      description: "例如：水母、霓虹、封面。",
    }),
  ],
  preview: {
    select: {
      title: "titleZh",
      subtitle: "category",
      media: "thumbnail",
    },
  },
});
