import { defineArrayMember, defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork",
  title: "作品管理",
  type: "document",
  groups: [
    { name: "basic", title: "基础信息", default: true },
    { name: "images", title: "图片" },
    { name: "details", title: "详情" },
  ],
  fields: [
    defineField({
      name: "siteKey",
      title: "所属网站标识",
      type: "string",
      initialValue: "main",
      hidden: true,
      readOnly: true,
      validation: (rule) => rule.required(),
      description: "系统字段，客户不用填写。",
    }),
    defineField({
      name: "featured",
      title: "设为精选作品",
      type: "boolean",
      initialValue: false,
      group: "basic",
      description: "开启后会优先显示在作品区顶部的大图位置。",
    }),
    defineField({
      name: "displayOrder",
      title: "排序数字",
      type: "number",
      initialValue: 100,
      group: "basic",
      description: "数字越小越靠前；不确定可保持默认。",
    }),
    defineField({
      name: "titleEn",
      title: "作品标题（英文）",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "titleZh", title: "作品标题（中文）", type: "string", group: "basic" }),
    defineField({
      name: "categoryRef",
      title: "稿件分类",
      type: "reference",
      to: [{ type: "artworkCategory" }],
      group: "basic",
      options: {
        filter: ({ document }) => ({
          filter: "_type == 'artworkCategory' && siteKey == $siteKey",
          params: { siteKey: document?.siteKey || "main" },
        }),
      },
      description: "先在左侧“稿件分类”里维护分类，再在这里选择。",
    }),
    defineField({
      name: "category",
      title: "旧分类（兼容用）",
      type: "string",
      group: "basic",
      hidden: true,
      options: {
        list: [
          { title: "主视觉", value: "Key Visual" },
          { title: "委托", value: "Commission" },
          { title: "界面细节", value: "UI Detail" },
          { title: "角色图", value: "Character Art" },
          { title: "设定参考", value: "Reference Sheet" },
          { title: "封面图", value: "Cover Art" },
          { title: "直播素材", value: "Stream Asset" },
          { title: "草稿", value: "Sketch" },
          { title: "个人作品", value: "Personal Work" },
        ],
      },
    }),
    defineField({
      name: "thumbnail",
      title: "作品缩略图",
      type: "image",
      options: { hotspot: true },
      group: "images",
      validation: (rule) => rule.required(),
      description: "用于作品列表展示。",
    }),
    defineField({
      name: "fullImage",
      title: "详情大图",
      type: "image",
      options: { hotspot: true },
      group: "images",
      description: "用于点击作品后的弹窗展示；不填时会使用缩略图。",
    }),
    defineField({
      name: "descriptionEn",
      title: "Notes / 说明（英文）",
      type: "text",
      rows: 3,
      group: "details",
    }),
    defineField({
      name: "descriptionZh",
      title: "Notes / 说明（中文）",
      type: "text",
      rows: 3,
      group: "details",
    }),
    defineField({ name: "roleEn", title: "Character / 角色（英文）", type: "string", group: "details" }),
    defineField({ name: "roleZh", title: "Character / 角色（中文）", type: "string", group: "details" }),
    defineField({ name: "colorPaletteEn", title: "Color / 色系（英文）", type: "string", group: "details" }),
    defineField({ name: "colorPaletteZh", title: "Color / 色系（中文）", type: "string", group: "details" }),
    defineField({ name: "createdAt", title: "Date / 日期", type: "date", group: "details" }),
    defineField({
      name: "tags",
      title: "标签（英文 / 默认）",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      group: "details",
      description: "例如：Jellyfish、Neon、Poster。",
    }),
    defineField({
      name: "tagsZh",
      title: "标签（中文）",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      group: "details",
      description: "例如：水母、霓虹、海报。",
    }),
  ],
  preview: {
    select: {
      title: "titleZh",
      subtitle: "categoryRef.titleZh",
      media: "thumbnail",
    },
  },
});
