import { defineArrayMember, defineField, defineType } from "sanity";

const colorRule = (rule: any) =>
  rule.regex(/^#[0-9a-fA-F]{6}$/, {
    name: "hex color",
    invert: false,
  });

function copyFields(name: string, title: string, type: "string" | "text" = "string") {
  return [
    defineField({
      name: `${name}En`,
      title: `${title}（英文）`,
      type,
      rows: type === "text" ? 2 : undefined,
    }),
    defineField({
      name: `${name}Zh`,
      title: `${title}（中文）`,
      type,
      rows: type === "text" ? 2 : undefined,
    }),
  ];
}

export const portfolioSite = defineType({
  name: "portfolioSite",
  title: "首页内容",
  type: "document",
  groups: [
    { name: "basic", title: "基础文字", default: true },
    { name: "images", title: "图片" },
    { name: "theme", title: "颜色设置" },
    { name: "copy", title: "页面文案" },
    { name: "about", title: "关于我" },
    { name: "links", title: "账号链接" },
  ],
  fields: [
    defineField({
      name: "siteKey",
      title: "网站标识",
      type: "string",
      initialValue: "main",
      hidden: true,
      readOnly: true,
      validation: (rule) => rule.required(),
      description: "系统字段，客户不用填写。",
    }),
    defineField({
      name: "adminTitle",
      title: "后台显示名称",
      type: "string",
      group: "basic",
      description: "用于后台左侧的网站列表名称。",
    }),
    defineField({ name: "nameEn", title: "网站名称（英文）", type: "string", group: "basic" }),
    defineField({ name: "nameZh", title: "网站名称（中文）", type: "string", group: "basic" }),
    defineField({ name: "subtitleEn", title: "副标题（英文）", type: "string", group: "basic" }),
    defineField({ name: "subtitleZh", title: "副标题（中文）", type: "string", group: "basic" }),
    defineField({ name: "descriptionEn", title: "网站简介（英文）", type: "text", rows: 3, group: "basic" }),
    defineField({ name: "descriptionZh", title: "网站简介（中文）", type: "text", rows: 3, group: "basic" }),
    defineField({
      name: "avatar",
      title: "头像",
      type: "image",
      options: { hotspot: true },
      group: "images",
    }),
    defineField({
      name: "backgroundImage",
      title: "首页顶部大图 / 海报",
      type: "image",
      options: { hotspot: true },
      group: "images",
      description: "控制网站最顶部的大图。关于我区域只显示头像和文字信息。",
    }),
    defineField({
      name: "themeBackground",
      title: "整体背景色",
      type: "string",
      group: "theme",
      description: "填写十六进制颜色，例如 #020611。",
      validation: colorRule,
    }),
    defineField({
      name: "themeSurface",
      title: "卡片/面板颜色",
      type: "string",
      group: "theme",
      description: "用于内容面板、作品卡片和按钮底色，例如 #0b1026。",
      validation: colorRule,
    }),
    defineField({
      name: "themePrimary",
      title: "主色",
      type: "string",
      group: "theme",
      description: "用于边框、光晕、当前选中状态，例如 #678cff。",
      validation: colorRule,
    }),
    defineField({
      name: "themeAccent",
      title: "强调色",
      type: "string",
      group: "theme",
      description: "用于 hover、发光和辅助装饰，例如 #6ce6ff。",
      validation: colorRule,
    }),
    defineField({
      name: "themeText",
      title: "主要文字色",
      type: "string",
      group: "theme",
      description: "建议使用浅色，例如 #e5f0ff。",
      validation: colorRule,
    }),
    defineField({ name: "roleEn", title: "定位/性别（英文）", type: "string", group: "basic" }),
    defineField({ name: "roleZh", title: "定位/性别（中文）", type: "string", group: "basic" }),
    defineField({ name: "auraEn", title: "生日（英文）", type: "string", group: "basic" }),
    defineField({ name: "auraZh", title: "生日（中文）", type: "string", group: "basic" }),
    defineField({ name: "styleEn", title: "生物/年龄（英文）", type: "string", group: "basic" }),
    defineField({ name: "styleZh", title: "生物/年龄（中文）", type: "string", group: "basic" }),
    defineField({
      name: "profileTagsEn",
      title: "个人标签（英文）",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      group: "basic",
    }),
    defineField({
      name: "profileTagsZh",
      title: "个人标签（中文）",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      group: "basic",
    }),
    defineField({
      name: "uiText",
      title: "页面固定文案",
      type: "object",
      group: "copy",
      description: "修改页面上的固定文字。留空时使用默认文字。",
      fields: [
        ...copyFields("aboutEyebrow", "关于我小标题"),
        ...copyFields("aboutTitle", "关于我标题"),
        ...copyFields("roleLabel", "资料字段 1 标签"),
        ...copyFields("auraLabel", "资料字段 2 标签"),
        ...copyFields("styleLabel", "资料字段 3 标签"),
        ...copyFields("linksEyebrow", "链接区小标题"),
        ...copyFields("linksTitle", "链接区标题"),
        ...copyFields("linksDescription", "链接区说明", "text"),
        ...copyFields("galleryEyebrow", "作品区小标题"),
        ...copyFields("galleryTitle", "作品区标题"),
        ...copyFields("galleryDescription", "作品区说明", "text"),
        ...copyFields("ongoingArchive", "右上角状态文字"),
        ...copyFields("featured", "精选标签"),
        ...copyFields("work", "普通作品标签"),
        ...copyFields("viewDetails", "查看详情按钮"),
        ...copyFields("home", "Home 按钮"),
        ...copyFields("backToTop", "返回顶部按钮"),
        ...copyFields("close", "关闭按钮"),
        ...copyFields("workDetails", "弹窗小标题"),
        ...copyFields("characterLabel", "弹窗 Character 标签"),
        ...copyFields("colorLabel", "弹窗 Color 标签"),
        ...copyFields("typeLabel", "弹窗 Type 标签"),
        ...copyFields("dateLabel", "弹窗 Date 标签"),
        ...copyFields("notesLabel", "弹窗 Notes 标签"),
        ...copyFields("noWorksTitle", "无作品标题"),
        ...copyFields("noWorksDescription", "无作品说明", "text"),
        ...copyFields("navProfile", "导航：个人档案"),
        ...copyFields("navProfileEyebrow", "导航：个人档案小字"),
        ...copyFields("navLinks", "导航：链接"),
        ...copyFields("navLinksEyebrow", "导航：链接小字"),
        ...copyFields("navGallery", "导航：作品"),
        ...copyFields("navGalleryEyebrow", "导航：作品小字"),
        ...copyFields("categoryAll", "分类：全部"),
        ...copyFields("categoryKeyVisual", "分类：主视觉"),
        ...copyFields("categoryCommission", "分类：委托"),
        ...copyFields("categoryUiDetail", "分类：界面细节"),
        ...copyFields("categoryCharacterArt", "分类：角色图"),
        ...copyFields("categoryReferenceSheet", "分类：设定参考"),
        ...copyFields("categoryCoverArt", "分类：封面图"),
        ...copyFields("categoryStreamAsset", "分类：直播素材"),
        ...copyFields("categorySketch", "分类：草稿"),
        ...copyFields("categoryPersonalWork", "分类：个人作品"),
      ],
    }),
    defineField({
      name: "aboutBlocks",
      title: "关于我信息块",
      type: "array",
      group: "about",
      of: [
        defineArrayMember({
          type: "object",
          title: "一条关于我信息",
          fields: [
            defineField({ name: "titleEn", title: "标题（英文）", type: "string" }),
            defineField({ name: "titleZh", title: "标题（中文）", type: "string" }),
            defineField({ name: "bodyEn", title: "内容（英文）", type: "text", rows: 2 }),
            defineField({ name: "bodyZh", title: "内容（中文）", type: "text", rows: 2 }),
          ],
          preview: {
            select: { title: "titleZh", subtitle: "titleEn" },
          },
        }),
      ],
    }),
    defineField({
      name: "links",
      title: "社交链接",
      type: "array",
      group: "links",
      of: [
        defineArrayMember({
          type: "object",
          title: "一个账号链接",
          fields: [
            defineField({ name: "name", title: "平台名称", type: "string" }),
            defineField({
              name: "icon",
              title: "图标字母",
              type: "string",
              validation: (rule) => rule.max(2),
              description: "例如 X、B、D、Y，前台会显示在圆形图标内。",
            }),
            defineField({ name: "url", title: "链接地址", type: "url" }),
            defineField({ name: "noteEn", title: "说明（英文）", type: "string" }),
            defineField({ name: "noteZh", title: "说明（中文）", type: "string" }),
          ],
          preview: {
            select: { title: "name", subtitle: "url" },
          },
        }),
      ],
    }),
  ],
  preview: {
    select: {
      title: "nameZh",
      subtitle: "siteKey",
      media: "avatar",
    },
  },
});
